#DO NOT TOUCH

config-ver: 1 #Please Don't Change It

#CONFIG

password: "changeme" #Keep It A Secret

console: "false" #Enable MCPEToConsole

#use " around commands for removing spaces between them

usage: "/console <pass..> <args..>" #Command Usage
